### ISSUE TITLE
Get Angular Material in here

### ISSUE THREAD

**Issue by jbw91** [jbw91/what-time-web#1]
Should we use the Angular Material 2 Alpha? Or just use the CSS from Angular Material 1?

**Comment by jbw91** [comment]
https://www.npmjs.com/~angular2-material Here's all the components published currently in the Material 2 alpha.

**Comment by jbw91** [comment]
The Material 2 components are looking pretty un-styled... I think we may be better off using Material 1. Or we could even use something like Materialize.

**Comment by gshigeto** [comment]
@jbw91 , I think as far as styling goes, Angular Material 1 CSS should do us fine. Could we also use Angular Material 2 alpha for built in packages?

**Comment by jbw91** [comment]
What do you mean "built in packages"?

**Comment by gshigeto** [comment]
Ignore 'built in packages'

**Comment by jbw91** [comment]
Uhhhh, I'm really confused now. Lol.

**Comment by gshigeto** [comment]
haha I think using Angular Material 1 for CSS or Materialize would fit us well.

**Comment by jbw91** [comment]
Okay lol. FORGET ANGULAR MATERIAL 2!!!!!!!!!

That's the key takeaway, yes?

**Comment by jbw91** [comment]
After discussion offline, the decision has been made.

**We will be using [Materialize](http://materializecss.com/).**

**Comment by jbw91** [comment]
There's also this: https://github.com/InfomediaLtd/angular2-materialize

Looks like it helps with the dynamic functionality. Not sure if it's necessary? We could try it out by itself first, then use this if it doesn't work the other way.

**Comment by drewctate** [comment]
Let's remember mobile first.  https://developers.google.com/web/fundamentals/design-and-ui/responsive/fundamentals/how-to-choose-breakpoints?hl=en

**Comment by jbw91** [comment]
Nice thing about Materialize is it already has breakpoints set.
